apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openclaw.fullname" . }}-init-scripts
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
data:
  init-config.sh: |
{{ tpl (.Files.Get "scripts/init-config.sh") . | nindent 4 }}
  init-skills.sh: |
{{ tpl (.Files.Get "scripts/init-skills.sh") . | nindent 4 }}
