{{- if and .Values.openclaw.secrets.apiKey.create (not .Values.openclaw.secrets.apiKey.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openclaw.secrets.apiKey.name }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.openclaw.secrets.apiKey.key }}: {{ .Values.openclaw.secrets.apiKey.value | quote }}
{{- end }}
