apiVersion: v1
kind: Service
metadata:
  name: {{ include "openclaw.fullname" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  {{- with .Values.gateway.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.gateway.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "openclaw.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
    {{- if .Values.sandbox.enabled }}
    - name: sandbox-vnc
      port: {{ .Values.gateway.service.sandboxPort }}
      targetPort: sandbox-vnc
      protocol: TCP
    {{- end }}
